### ISSUE TITLE
Matching G Drive Spalten mit zusätzlichen Meta-Felder 

### ISSUE THREAD

**Issue by alexanderkoenitz** [NicoKnoll/BLNFMCalSync#3]
# _ATT{Line Up} = Line Up
# _ATT{Short Description} = Kurzbeschreibung
# _ATT{Preis} = Preis
# _ATT{Stil} = Stil

Muss dazu noch ein ID-Feld hinterlegt werden - mit der ID im Spreadsheet? Wie muss es heissen?

**Comment by nicoknoll** [comment]
Done.
