### ISSUE TITLE
Markiere abhängig aus Inhalt Spalte "Veranstaltungstyp" eine Kategorie

### ISSUE THREAD

**Issue by alexanderkoenitz** [NicoKnoll/BLNFMCalSync#5]
• Ausstellung
• Bar
• Konzert
• Party
• Sonstiges (Falls keine andere vorhandene Kategorie matcht) (dann sollte auch keine andere Kategorie gekreuzt sein wie 

Die Kategorien sollten erweiterbar sein: wenn eine in WP zusätzlich "eröffnet" wird, sollte sie zu Verfügung stehen.

**Comment by nicoknoll** [comment]
Done.
