### ISSUE TITLE
Ermögliche die Synchronisation mehrerer Spreadsheets

### ISSUE THREAD

**Issue by alexanderkoenitz** [NicoKnoll/BLNFMCalSync#7]
Wir wollen die Bearbeitung der Termine auf mehr als ein Dokument aufteilen, damit wir die Rechte geschickter aufteilen können.

Dazu müsste es den Mechanismus geben, dass mehrere Files einzeln und getrennt synchronsiert werden können.

**Comment by nicoknoll** [comment]
Done.

**Comment by alexanderkoenitz** [comment]
Wo können die Google Docs IDs der Dokumente eingegeben werden?
